# Generated by Django 2.2.9 on 2023-02-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220612_1838'),
        ('posts', '0002_auto_20230215_1804'),
    ]

    operations = [
    ]
